"use client";
import { useMemo, useState } from "react";
import rawMap from "../data/tilerush-map.json";
import { DEFAULT_CONFIG } from "../domain/defaults";
import type { SimulationConfig } from "../domain/types";
import { loadCanonicalMap } from "../map/map-loader";
import { buildMatchedPopulation } from "../population/match-alliances";
import { calculateMatchMetrics, summarizeBatch } from "../analytics/metrics";
import { runSimulation } from "../simulation/engine";
import { HexMapCanvas } from "./HexMapCanvas";
const MAP = loadCanonicalMap(rawMap);
const TABS = ["仿真总览", "行动力与节奏", "任务与奖励", "玩家与联盟排名", "批量实验"] as const;
const COLORS = ["#e85d55", "#3989dd", "#e5a62d"];
function formatHour(value: number | null) { if (value === null) return "未发生"; const h = Math.floor(value); return `${h}小时${Math.round((value-h)*60)}分`; }
export function SimulationDashboard() {
  const [tab,setTab]=useState<(typeof TABS)[number]>("仿真总览"), [draft,setDraft]=useState<SimulationConfig>(structuredClone(DEFAULT_CONFIG)), [applied,setApplied]=useState<SimulationConfig>(structuredClone(DEFAULT_CONFIG)), [seed,setSeed]=useState(DEFAULT_CONFIG.seed), [hour,setHour]=useState(48), [batch,setBatch]=useState<ReturnType<typeof summarizeBatch>|null>(null);
  const result=useMemo(()=>{const population=buildMatchedPopulation(applied,seed);return runSimulation({map:MAP,config:applied,population,seed});},[applied,seed]);
  const metrics=useMemo(()=>calculateMatchMetrics(result,applied),[result,applied]), snapshot=result.snapshots[Math.min(48,Math.round(hour))];
  const setNumber=(key:string,value:number)=>setDraft(c=>{const n=structuredClone(c); if(key==="attack")n.ap.attackCost=value;if(key==="recover")n.ap.recoveryAmount=value;if(key==="safe")n.occupation.safeDistance=value;if(key==="distance")n.occupation.secondsPerExcessHex=value;return n;});
  const rerun=()=>{setApplied(structuredClone(draft));setSeed(v=>v+1);setBatch(null);};
  const runBatch=()=>{const rows=Array.from({length:10},(_,i)=>{const s=seed+i+1,p=buildMatchedPopulation(draft,s),r=runSimulation({map:MAP,config:draft,population:p,seed:s}),m=calculateMatchMetrics(r,draft);return{firstPvpHour:m.firstPvpHour,dominance:m.dominance};});setBatch(summarizeBatch(rows));};
  return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">TILERUSH / NUMERICAL LAB</span><h1>海岛夺金 · 数值实验室</h1></div><div className="seed">随机种子 <strong>{seed}</strong></div></header>
    <nav className="tabs" role="tablist" aria-label="分析页面">{TABS.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    <section className="workspace"><aside className="control-panel"><div className="panel-heading"><span>参数控制</span><button className="ghost" onClick={()=>setDraft(structuredClone(DEFAULT_CONFIG))}>恢复默认</button></div>
      <label>进攻 AP 消耗 <output>{draft.ap.attackCost}</output><input type="range" min="5" max="30" value={draft.ap.attackCost} onChange={e=>setNumber("attack",+e.target.value)}/></label>
      <label>每次 AP 恢复 <output>{draft.ap.recoveryAmount}</output><input type="range" min="10" max="100" step="5" value={draft.ap.recoveryAmount} onChange={e=>setNumber("recover",+e.target.value)}/></label>
      <label>安全距离 <output>{draft.occupation.safeDistance} 格</output><input type="range" min="0" max="10" value={draft.occupation.safeDistance} onChange={e=>setNumber("safe",+e.target.value)}/></label>
      <label>超距增量 <output>{draft.occupation.secondsPerExcessHex} 秒/格</output><input type="range" min="0" max="120" step="5" value={draft.occupation.secondsPerExcessHex} onChange={e=>setNumber("distance",+e.target.value)}/></label>
      <div className="rule-card"><span>匹配边界</span><strong>最强 / 最弱 ≤ 1.25</strong><small>300名玩家 · 每盟100人</small></div><button className="primary" onClick={rerun}>重新运行单局</button></aside>
      <section className="main-stage">{tab==="仿真总览"&&<><div className="stage-title"><div><span className="status-dot"/>T+{snapshot.hour}:00 战场快照</div><span>{result.events.length} 次真实换主</span></div><HexMapCanvas map={MAP} snapshot={snapshot}/><label className="timeline">回放时间 <output>T+{hour}h</output><input type="range" min="0" max="48" value={hour} onChange={e=>setHour(+e.target.value)}/></label><div className="alliance-bars">{result.alliances.sort((a,b)=>a.id-b.id).map((a,i)=><div key={a.id}><span>{a.name}</span><i style={{width:`${Math.max(4,snapshot.scores[i]/55)}%`,background:COLORS[i]}}/><strong>{snapshot.scores[i].toLocaleString()}</strong></div>)}</div></>}
      {tab==="行动力与节奏"&&<div className="analysis-grid"><article><h2>行动力供需</h2><div className="big-number">{Math.round(metrics.apUtilization*100)}%</div><p>理论行动机会使用率</p><div className="meter"><i style={{width:`${metrics.apUtilization*100}%`}}/></div></article><article><h2>首次有效 PvP</h2><div className="big-number">{formatHour(metrics.firstPvpHour)}</div><p>目标 3～6小时 · {metrics.firstPvpStatus}</p></article><article className="wide"><h2>占领时长公式</h2><code>基础时长 + max(0, 距大本营距离 − {applied.occupation.safeDistance}) × {applied.occupation.secondsPerExcessHex}s</code><p>先锋营只提供连地，不重置距离。</p></article></div>}
      {tab==="任务与奖励"&&<div className="reward-view"><div className="coverage-chart">{applied.tasks.thresholds.map((t,i)=><div key={t}><i style={{height:`${metrics.taskCoverage[i]*100}%`}}/><span>{t}</span><b>{Math.round(metrics.taskCoverage[i]*100)}%</b></div>)}</div><div className="budget-bar"><i style={{width:"40%"}}>前段 40%</i><i style={{width:"35%"}}>中段 35%</i><i style={{width:"20%"}}>高段 20%</i><i style={{width:"5%"}}>5%</i></div><p>奖励总预算固定；总奖励倍率独立控制。</p></div>}
      {tab==="玩家与联盟排名"&&<div className="ranking-view"><div className="alliance-ranking">{[...result.alliances].sort((a,b)=>a.rank-b.rank).map(a=><article key={a.id}><span>第 {a.rank} 名</span><h2>{a.name}</h2><strong>{a.snapshotScore.toLocaleString()}</strong><small>累计贡献 {a.contributionScore.toLocaleString()} · {a.tileCount}格</small></article>)}</div><div className="table-wrap"><table><thead><tr><th>排名</th><th>玩家</th><th>联盟</th><th>战力</th><th>活跃</th><th>行动</th><th>战功</th><th>占领</th><th>总分</th></tr></thead><tbody>{result.players.map((p,i)=><tr key={p.id}><td>{i+1}</td><td>{p.name}</td><td>{p.allianceId}</td><td>{p.power.toLocaleString()}</td><td>{p.activityTier}</td><td>{p.actions}</td><td>{p.battleScore}</td><td>{p.occupationScore}</td><td><strong>{p.personalScore}</strong></td></tr>)}</tbody></table></div></div>}
      {tab==="批量实验"&&<div className="batch-view"><h2>10局快速稳定性实验</h2><p>连续随机种子重复生成玩家与对局，排除单局偶然性。</p><button className="primary compact" onClick={runBatch}>运行10局实验</button>{batch&&<div className="batch-results"><article><span>首次 PvP 中位数</span><strong>{formatHour(batch.firstPvpMedian)}</strong></article><article><span>3～6h 命中率</span><strong>{Math.round(batch.firstPvpTargetRate*100)}%</strong></article><article><span>单边统治风险</span><strong>{Math.round(batch.dominanceRisk*100)}%</strong></article></div>}</div>}</section>
      <aside className="insight-panel"><span className="eyebrow">DECISION SIGNALS</span><div className={`signal ${metrics.firstPvpStatus==="target"?"good":"warn"}`}><span>首次有效 PvP</span><strong>{formatHour(metrics.firstPvpHour)}</strong><small>目标：3～6小时</small></div><div className={metrics.dominance<.6?"signal good":"signal danger"}><span>领先方地图价值占比</span><strong>{Math.round(metrics.dominance*100)}%</strong><small>≥60%视为高风险</small></div><div className="signal"><span>个人积分中位数</span><strong>{Math.round(metrics.medianPersonalScore)}</strong><small>任务第4档：520</small></div><div className="diagnosis"><strong>本局诊断</strong><p>{metrics.firstPvpStatus==="late"?"接敌偏晚，优先检查行动消耗与安全距离。":metrics.dominance>=.6?"领先优势偏大，建议提高纵深惩罚。":"节奏与地图控制暂未出现明显红线。"}</p></div></aside>
    </section></main>;
}
