"use client";
import { useMemo, useState } from "react";
import rawMap from "../data/tilerush-map.json";
import { calculateMatchMetrics, summarizeBatch } from "../analytics/metrics";
import { DEFAULT_CONFIG } from "../domain/defaults";
import type { PowerTier, SimulationConfig } from "../domain/types";
import { loadCanonicalMap } from "../map/map-loader";
import { buildMatchedPopulation } from "../population/match-alliances";
import { moraleMultiplier } from "../simulation/morale";
import { runSimulation } from "../simulation/engine";
import { HexMapCanvasV2 } from "./HexMapCanvasV2";

const MAP=loadCanonicalMap(rawMap), TABS=["仿真总览","行动力与节奏","战斗与士气","任务与奖励","玩家与联盟排名","批量实验"] as const;
const COLORS=["#ef5d52","#3b96ef","#e7aa2c"], TIERS:PowerTier[]=["low","mid","high"], TIER_NAME={low:"低战力",mid:"中战力",high:"高战力"};
const simulate=(config:SimulationConfig,seed:number)=>runSimulation({map:MAP,config,population:buildMatchedPopulation(config,seed),seed});
const fmt=(value:number|null)=>value===null?"未发生":Math.floor(value)+"小时"+Math.round((value-Math.floor(value))*60)+"分";
const compact=(value:number)=>new Intl.NumberFormat("zh-CN",{notation:value>999999?"compact":"standard",maximumFractionDigits:1}).format(value);

export function SimulationDashboardV2(){
 const [tab,setTab]=useState<(typeof TABS)[number]>("仿真总览"),[draft,setDraft]=useState<SimulationConfig>(()=>structuredClone(DEFAULT_CONFIG)),[applied,setApplied]=useState<SimulationConfig>(()=>structuredClone(DEFAULT_CONFIG)),[seed,setSeed]=useState(DEFAULT_CONFIG.seed),[result,setResult]=useState(()=>simulate(DEFAULT_CONFIG,DEFAULT_CONFIG.seed)),[hour,setHour]=useState(48),[dirty,setDirty]=useState(false),[running,setRunning]=useState(false),[batch,setBatch]=useState<ReturnType<typeof summarizeBatch>|null>(null);
 const metrics=useMemo(()=>calculateMatchMetrics(result,applied),[result,applied]), snapshot=result.snapshots[Math.min(result.snapshots.length-1,Math.round(hour))], leader=[...result.alliances].sort((a,b)=>a.rank-b.rank)[0];
 const change=(fn:(config:SimulationConfig)=>void)=>{setDraft(current=>{const next=structuredClone(current);fn(next);return next});setDirty(true)};
 const rerun=()=>{setRunning(true);setTimeout(()=>{const nextSeed=seed+1,next=structuredClone(draft);setResult(simulate(next,nextSeed));setApplied(next);setSeed(nextSeed);setDirty(false);setRunning(false);setBatch(null)},0)};
 const chance=(a:PowerTier,d:PowerTier)=>{const attack=applied.population.basePower[a]*moraleMultiplier(100,applied.morale),defense=applied.population.basePower[d]*moraleMultiplier(150,applied.morale);return 1/(1+Math.exp(-applied.combat.winProbabilitySlope*Math.log(attack/defense)))};
 const recent=result.timeline.filter(event=>event.second<=hour*3600).slice(-7).reverse();
 return <main className="command-shell">
  <header className="command-header"><div className="brand"><span className="brand-icon">?</span><div><small>TILERUSH · NUMERICAL LAB</small><h1>海岛夺金 数值指挥中心</h1></div></div><div className="run-meta"><span>随机种子 <b>{seed}</b></span><i className={dirty?"dirty":""}>{dirty?"参数待应用":"结果已同步"}</i><button onClick={rerun} disabled={running}>{running?"仿真运行中…":"重新运行单局"}</button></div></header>
  <section className="kpi-strip"><article><span>首次有效 PvP</span><strong>{fmt(metrics.firstPvpHour)}</strong><small>目标 3～6 小时</small></article><article><span>行动力使用率</span><strong>{Math.round(metrics.apUtilization*100)}%</strong><small>活跃度自然产生</small></article><article><span>活跃战线</span><strong>{metrics.activeFronts}</strong><small>{metrics.uniqueContestedTiles} 个争夺地格</small></article><article><span>争夺集中度</span><strong>{metrics.contestConcentration.toFixed(3)}</strong><small>越低越分散</small></article><article><span>领先联盟</span><strong style={{color:COLORS[leader.id-1]}}>{leader.name}</strong><small>{leader.snapshotScore} 地图分</small></article></section>
  <div className="command-tabs" role="tablist" aria-label="分析页面">{TABS.map(name=><button key={name} role="tab" aria-selected={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div>
  <section className="command-workspace">
   <aside className="parameter-rail"><div className="rail-title"><div><small>MODEL CONTROL</small><h2>参数实验台</h2></div><button onClick={()=>{setDraft(structuredClone(DEFAULT_CONFIG));setDirty(true)}}>恢复默认</button></div>
    <details open><summary>人口与战力</summary><label>中战力占比 <output>{Math.round(draft.population.powerShares.mid*100)}%</output><input type="range" min="10" max="35" value={draft.population.powerShares.mid*100} onChange={e=>change(c=>{c.population.powerShares.mid=+e.target.value/100;c.population.powerShares.low=1-c.population.powerShares.mid-c.population.powerShares.high})}/></label><label>高战力占比 <output>{Math.round(draft.population.powerShares.high*100)}%</output><input type="range" min="2" max="15" value={draft.population.powerShares.high*100} onChange={e=>change(c=>{c.population.powerShares.high=+e.target.value/100;c.population.powerShares.low=1-c.population.powerShares.mid-c.population.powerShares.high})}/></label><label>高档均值 <output>{compact(draft.population.basePower.high)}</output><input type="range" min="1100000" max="2200000" step="50000" value={draft.population.basePower.high} onChange={e=>change(c=>{c.population.basePower.high=+e.target.value})}/></label></details>
    <details open><summary>行动力与占领</summary><label>AP 消耗 <output>{draft.ap.attackCost}</output><input type="range" min="5" max="25" value={draft.ap.attackCost} onChange={e=>change(c=>{c.ap.attackCost=+e.target.value})}/></label><label>占领节奏倍率 <output>{draft.occupation.paceMultiplier}×</output><input type="range" min="1" max="60" value={draft.occupation.paceMultiplier} onChange={e=>change(c=>{c.occupation.paceMultiplier=+e.target.value})}/></label><label>超距增量 <output>{draft.occupation.secondsPerExcessHex}s</output><input type="range" min="0" max="120" step="5" value={draft.occupation.secondsPerExcessHex} onChange={e=>change(c=>{c.occupation.secondsPerExcessHex=+e.target.value})}/></label></details>
    <details><summary>战斗与士气</summary><label>士气下限 <output>{draft.morale.min}</output><input type="range" min="0" max="80" value={draft.morale.min} onChange={e=>change(c=>{c.morale.min=+e.target.value})}/></label><label>每格衰减 <output>{draft.morale.lossPerExcessHex}</output><input type="range" min="0" max="10" step=".5" value={draft.morale.lossPerExcessHex} onChange={e=>change(c=>{c.morale.lossPerExcessHex=+e.target.value})}/></label><label>每胜衰减 <output>{draft.morale.lossPerWin}</output><input type="range" min="0" max="10" step=".5" value={draft.morale.lossPerWin} onChange={e=>change(c=>{c.morale.lossPerWin=+e.target.value})}/></label><label>战斗间隔 <output>{draft.combat.battleIntervalSeconds}s</output><input type="range" min="5" max="30" step="5" value={draft.combat.battleIntervalSeconds} onChange={e=>change(c=>{c.combat.battleIntervalSeconds=+e.target.value})}/></label></details>
    <div className="rule-box"><span>匹配边界</span><strong>最强 / 最弱 ≤ 1.25</strong><small>300 玩家 · 每盟 100 · 六编队</small></div>
   </aside>
   <section className="analysis-stage">
    {tab==="仿真总览"&&<div className="overview-grid"><section className="map-panel"><div className="section-title"><b>T+{snapshot.hour.toFixed(0)}h 战场态势</b><span>{snapshot.activeBattles} 场战斗</span></div><HexMapCanvasV2 map={MAP} snapshot={snapshot}/><label className="timeline"><span>战局回放</span><output>T+{hour}h</output><input aria-label="回放时间" type="range" min="0" max="48" value={hour} onChange={e=>setHour(+e.target.value)}/></label><div className="map-legend"><strong>地格图例</strong>{["普通","资源晶体","核心","山地","水域","交战中"].map((name,index)=><span key={name}><i className={"legend l"+index}/>{name}</span>)}</div></section><aside className="event-list"><div className="section-title"><b>战场事件流</b><span>10 秒粒度</span></div>{recent.map((event,index)=><article key={index}><time>T+{Math.floor(event.second/3600)}:{String(Math.floor(event.second%3600/60)).padStart(2,"0")}</time><div><b>{event.type==="battle"?"队列交战":event.type==="capture"?"完成占领":event.type==="dispatch"?"部队入场":"行动力恢复"}</b><span>{event.tileId?"#"+event.tileId+" 地格":""}{event.troopsKilled?" · 击杀 "+compact(event.troopsKilled):""}</span></div></article>)}</aside></div>}
    {tab==="行动力与节奏"&&<div className="card-grid"><article className="metric-card"><span>总体 AP 使用率</span><strong>{Math.round(metrics.apUtilization*100)}%</strong><small>恢复溢出 {Math.round(metrics.apOverflowRate*100)}%</small></article><article className="metric-card"><span>首次 PvP</span><strong>{fmt(metrics.firstPvpHour)}</strong><small>占领倍率 {applied.occupation.paceMultiplier}×</small></article><section className="wide-card"><div className="section-title"><b>不同活跃玩家的实际行动力使用</b><span>结果指标，不是节奏旋钮</span></div><div className="activity-bars">{metrics.activityUtilization.map((row,index)=><div key={row.tier}><span>{["极低","休闲","普通","活跃","核心"][index]}<small>{row.players} 人</small></span><i><b style={{width:row.utilization*100+"%"}}/></i><strong>{Math.round(row.utilization*100)}%</strong></div>)}</div></section><section className="wide-card formula"><b>唯一 PvP 节奏控制公式</b><code>(基础时长 + max(0, 基地距离 ? {applied.occupation.safeDistance}) × {applied.occupation.secondsPerExcessHex}s) × {applied.occupation.paceMultiplier}</code></section></div>}
    {tab==="战斗与士气"&&<div className="combat-grid"><section className="formula-card"><small>CURRENT GDD FORMULA</small><h2>士气伤害系数</h2><code>{applied.morale.coefficientIntercept.toFixed(4)} + {applied.morale.coefficientSlope.toFixed(4)} × 士气/100</code><div className="anchors">{[20,100,150].map(value=><span key={value}>士气 {value}<b>{Math.round(moraleMultiplier(value,applied.morale)*100)}%</b></span>)}</div><p>超过安全距离每格 ?{applied.morale.lossPerExcessHex}，每次连胜 ?{applied.morale.lossPerWin}。</p></section><section className="matrix-card"><div className="section-title"><b>战力档对战胜率</b><span>进攻士气100 / 防守150</span></div><table><thead><tr><th>进 / 防</th>{TIERS.map(t=><th key={t}>{TIER_NAME[t]}</th>)}</tr></thead><tbody>{TIERS.map(a=><tr key={a}><th>{TIER_NAME[a]}</th>{TIERS.map(d=><td key={d}>{Math.round(chance(a,d)*100)}%</td>)}</tr>)}</tbody></table></section><section className="wide-card battle-facts"><span>单队 <b>{compact(applied.combat.troopSize)}</b></span><span>每场 <b>{applied.combat.battleIntervalSeconds} 秒</b></span><span>战功 <b>{compact(applied.scoring.killsPerPoint)}兵 : 1</b></span><span>本局 <b>{metrics.pvpEvents} 场</b></span></section></div>}
    {tab==="任务与奖励"&&<section className="task-panel"><div className="section-title"><div><b>任务—积分—奖励耦合</b><p>修改阈值与奖励价值后重新仿真。</p></div><span>统一奖励价值单位</span></div><div className="task-table"><table><thead><tr><th>档位</th><th>积分阈值</th><th>奖励价值</th><th>达成率</th><th>边际价值/分</th></tr></thead><tbody>{draft.tasks.thresholds.map((threshold,index)=><tr key={index}><td>任务 {index+1}</td><td><input type="number" value={threshold} onChange={e=>change(c=>{c.tasks.thresholds[index]=+e.target.value})}/></td><td><input type="number" value={draft.rewards.taskValues[index]} onChange={e=>change(c=>{c.rewards.taskValues[index]=+e.target.value})}/></td><td><div className="coverage"><i style={{width:metrics.taskCoverage[index]*100+"%"}}/><span>{Math.round(metrics.taskCoverage[index]*100)}%</span></div></td><td>{metrics.rewardMarginalValue[index].toFixed(3)}</td></tr>)}</tbody></table></div><div className="reward-bar"><span>前段40%</span><span>中段35%</span><span>高段20%</span><span>顶段5%</span></div></section>}
    {tab==="玩家与联盟排名"&&<section className="rank-panel"><div className="podium">{[...result.alliances].sort((a,b)=>a.rank-b.rank).map(a=><article key={a.id} style={{borderColor:COLORS[a.id-1]}}><span>第 {a.rank} 名</span><h2>{a.name}</h2><strong>{a.snapshotScore}</strong><small>地图分 · {a.tileCount}格 · 累计贡献 {a.contributionScore}</small></article>)}</div><div className="rank-table"><table><thead><tr><th>#</th><th>玩家</th><th>联盟</th><th>战力</th><th>活跃</th><th>行动</th><th>AP使用</th><th>击杀兵量</th><th>战功</th><th>占领</th><th>连胜</th><th>总分</th></tr></thead><tbody>{result.players.map((p,index)=><tr key={p.id}><td>{index+1}</td><td><b>{p.name}</b><small>{TIER_NAME[p.powerTier]}</small></td><td><i style={{background:COLORS[p.allianceId-1]}}/>{p.allianceId}</td><td>{compact(p.power)}</td><td>{p.activityTier}</td><td>{p.actions}</td><td>{Math.round(p.apSpent/Math.max(1,p.apSupply)*100)}%</td><td>{compact(p.kills)}</td><td>{p.battleScore}</td><td>{p.occupationScore}</td><td>{p.maxWinStreak}</td><td><b>{p.personalScore}</b></td></tr>)}</tbody></table></div></section>}
    {tab==="批量实验"&&<section className="batch-panel"><small>MONTE CARLO EXPERIMENT</small><h2>多随机种子稳定性实验</h2><p>重复生成 300 名玩家与完整 48 小时战局，排除单局偶然性。</p><div><select value={draft.batchRuns} onChange={e=>change(c=>{c.batchRuns=+e.target.value as 10|50|100})}><option value="10">10局快速</option><option value="50">50局标准</option><option value="100">100局高置信</option></select><button disabled={running} onClick={()=>{setRunning(true);setTimeout(()=>{const rows=Array.from({length:draft.batchRuns},(_,i)=>{const r=simulate(draft,seed+i+1),m=calculateMatchMetrics(r,draft);return{firstPvpHour:m.firstPvpHour,dominance:m.dominance}});setBatch(summarizeBatch(rows));setRunning(false)},0)}}>{running?"实验运行中…":"运行批量实验"}</button></div>{batch&&<div className="batch-results"><article><span>PvP中位数</span><strong>{fmt(batch.firstPvpMedian)}</strong></article><article><span>目标命中率</span><strong>{Math.round(batch.firstPvpTargetRate*100)}%</strong></article><article><span>统治风险</span><strong>{Math.round(batch.dominanceRisk*100)}%</strong></article></div>}</section>}
   </section>
   <aside className="decision-rail"><small>DECISION SIGNALS</small><article><span>节奏诊断</span><strong>{metrics.firstPvpStatus==="target"?"命中目标":metrics.firstPvpStatus==="early"?"接敌过早":"接敌偏晚"}</strong><small>{fmt(metrics.firstPvpHour)}</small></article><article><span>行动力供需</span><strong>{Math.round(metrics.apUtilization*100)}%</strong><small>目标约50%</small></article><article><span>争夺集中度</span><strong>{metrics.contestConcentration.toFixed(3)}</strong><small>{metrics.uniqueContestedTiles}格</small></article><div className="diagnosis"><b>本局建议</b><p>{metrics.firstPvpStatus==="early"?"提高占领节奏倍率，不要压低玩家行动率。":metrics.contestConcentration>=.35?"提高拥堵惩罚或增加战线。":metrics.apOverflowRate>.4?"恢复溢出偏高，可调整恢复量或上限。":"节奏、战线和行动力处于健康区间。"}</p></div></aside>
  </section>
 </main>
}
